apiVersion: v1
kind: Pod
metadata:
  name: kaniko-debug
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args:
      - "--dockerfile=Dockerfile"
      - "--context=dir:///workspace/my-node-app"
      - "--destination=localhost:5000/my-node-app:latest"
      - "--insecure"
      - "--skip-tls-verify"
    volumeMounts:
      - name: app-volume
        mountPath: /workspace/my-node-app
  volumes:
    - name: app-volume
      hostPath:
        path: /home/abhi/my-node-app
        type: Directory
  restartPolicy: Never
